### ISSUE TITLE
Reversed stars

### ISSUE THREAD

**Issue by mladjan** [dlinsin/DLStarRating#10]
I just copied and pasted sample code from demo app into my app, and stars began reversed :|
Screenshot: http://cl.ly/0w0u3h0x330q3J3d0523

What can affect this?

**Comment by mladjan** [comment]
I gave bad names for stars xD
My bad, delete this please :)

**Comment by dlinsin** [comment]
Maybe an index problem? Can you disclose your code here?

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com
