### ISSUE TITLE
how to change the size of stars?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [dlinsin/DLStarRating#11]
is it possible to change the size, actually decrease?

**Comment by dlinsin** [comment]
What exactly do you mean? Programmatically change the size? Or just use smaller stars?

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com

**Comment by KanybekMomukeyev** [comment]
Just use smaller stars.

**Comment by dlinsin** [comment]
You can use smaller stars without any problems!  If you want to use fractional stars, you have to provide images with width divisible by 10. see here: https://github.com/dlinsin/DLStarRating/issues/9#issuecomment-4438728

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com

**Comment by KanybekMomukeyev** [comment]
thanks
