### ISSUE TITLE
Slow working DLStarView in a UITableViewCell

### ISSUE THREAD

**Issue by KanybekMomukeyev** [dlinsin/DLStarRating#14]
How to fix this, i have added to my custom UITableViewCell, and this
is very slow working.
Is there any special property for this ?

**Comment by dlinsin** [comment]
I don't think DLStarRating is the right choice. It uses UIViews and no custom drawing, which means there's a lot of compositing of layers going on. 

I'm planing to custom draw the star rating component in the future, but right now there's nothing much you can do. 

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com
