### ISSUE TITLE
How to set rater to read-only?

### ISSUE THREAD

**Issue by ghost** [dlinsin/DLStarRating#18]
Greetings,

I'm trying to set the rater to read-only.

I have it set up so that the user can rate, but then I want to show them the DLStarRating read-only.

How to do this?

Many thanks in advance,

**Comment by dlinsin** [comment]
Since `DLStarRatingControl` is a subclass of `UIControl` you can simple use the method `userInteractionEnabled`.

``` objective-c
DLStarRatingControl *customNumberOfStars = [[DLStarRatingControl alloc] initWithFrame:CGRectMake(0, 154, 320, 153) andStars:5 isFractional:YES];
customNumberOfStars.userInteractionEnabled = NO;
```
