### ISSUE TITLE
fractional star

### ISSUE THREAD

**Issue by nurey** [dlinsin/DLStarRating#6]
Is there a plan to add support for displaying a half rating? eg. a rating of 3.5?

**Comment by dlinsin** [comment]
Great idea. So far there are no plans, however, I'll look into it. 

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com

**Comment by dlinsin** [comment]
It should be pretty easy to implement, however at the moment I don't have the time - any help if welcome.
