### ISSUE TITLE
fractional rating doesn't work for small images (11x11)

### ISSUE THREAD

**Issue by nurey** [dlinsin/DLStarRating#9]
There seems to be a problem when using small images. 11x11 px in my case. Not sure why. 
Here's how it looks like rendered with DLStarRatingControl -- http://a.yfrog.com/img812/9646/l37.png

Here's the 11x11 star -- http://a.yfrog.com/img576/7623/qr8d.png

**Comment by dlinsin** [comment]
Thanks, I'll look into it as soon as I get around

**Comment by dlinsin** [comment]
I could reproduce this if `isFractional` is set to _YES_ if you set it to _NO_ you should be okay:

``` objective-c
[[DLStarRatingControl alloc] initWithFrame:CGRectMake(0, 154, 320, 153) andStars:5 isFractional:NO];
```

I'll investigate further, but the code was provided by @kuchmiyalex and I need to dig into it first.

**Comment by dlinsin** [comment]
@kuchmiyalex I could use your support on this. The method `- (UIImage *)croppedImage:(UIImage*)image` in `DLStarView.m` doesn't work with smaller images. I don't really understand why.

**Comment by kuchmiyalex** [comment]
You should use image with width fractional by 10, so it could be 10x10/20x20/30x30px image.

**Comment by dlinsin** [comment]
Thanks for the feedback, I'll add it to the docs. 

with kind regards,

David Linsin

---

// web: http://dlinsin.github.com

**Comment by nurey** [comment]
Great. Thanks Alex. I goess it would also work well with images in increments of 5 if you set kNumberOfFractions to 5.
